spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://hr-auth:8081
          predicates:
            - Path=/api/auth/**,/api/auth/password-reset/request
          filters:
            - StripPrefix=1

        - id: hr-public
          uri: http://hr-backend:8082
          predicates:
            - Path=/api/v1/company-applications/submit,/api/v1/health
          filters:
            - StripPrefix=2

        - id: hr-files
          uri: http://hr-backend:8082
          predicates:
            - Path=/api/v1/files/**

        - id: hr
          uri: http://hr-backend:8082
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
            - JwtAuthenticationFilter

        - id: notification-api
          uri: http://hr-notification:8083
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

        - id: chatbot
          uri: http://hr-chatbot:8000
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter

jwt:
  secret-key: ${JWT_SECRET_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

internal:
  token: ${INTERNAL_TOKEN}
